name: deploy

on:
  push:
    branches: master

jobs:
  main:
    runs-on: macos-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set up ssb
        run: brew install ssb
